app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function(){
    return View::make('login.index');
});

Route::get('home', 'HomeController@index');

Route::controllers([
	'auth' => 'Auth\AuthController',
	'password' => 'Auth\PasswordController',
]);

Route::group(['namespace' => 'API'], function()
{
    Route::get('departements', [
        'as' => 'departements.show',
        'uses' => 'DepartementsController@show'
    ]);

    Route::post('attendance/check', [
        'as' => 'attendance.check',
        'uses' => 'AttendanceController@show'
    ]);

    Route::post('attendance/store', [
        'as' => 'attendance.store',
        'uses' => 'AttendanceController@store'
    ]);

    Route::resource('religions', 'ReligionController', ['only' => 'index']);
    Route::resource('gender', 'GenderController', ['only' => 'index']);
});

Route::get('token', function()
{
    return view('layouts.default');
});

Route::group(['namespace' => 'Snappy'], function()
{
    Route::get('login', [
        'as' => 'login.index',
        'uses' => 'SessionController@index'
    ]);

    Route::post('login', [
        'as' => 'login.store',
        'uses' => 'SessionController@store'
    ]);

    Route::resource('dashboard', 'DashboardController', ['only' => 'index']);
    Route::resource('employee', 'EmployeeController');
});

Route::get('user', function()
{
    $user = \SnapClock\Employee::create([
        'username' => 'sugeng',
        'firstname' => 'Sugeng',
        'lastname' => 'Supriyadi',
        'email' => 'me@sugeng.me'
    ]);

    $user->password = Hash::make('secret');
    $user->save();
});

resources/views/layouts/partials/navigation.blade.php
<!-- BEGIN SIDEBAR MENU -->
<ul class="page-sidebar-menu page-sidebar-menu-hover-submenu " data-keep-expanded="false" data-auto-scroll="true" data-slide-speed="200">
    <li class="start active ">
        <a href="index.html">
            <i class="icon-home"></i>
            <span class="title">Dashboard</span>
            <span class="selected"></span>
        </a>
    </li>
    <li>
        <a href="javascript:;">
            <i class="icon-basket"></i>
            <span class="title">Karyawan</span>
            <span class="arrow "></span>
        </a>
        <ul class="sub-menu">
            <li>
                <a href="{!! route('employee.index') !!}">
                    <i class="icon-home"></i>
                    Database Karyawan</a>
            </li>
        </ul>
    </li>
    <li class="last ">
        <a href="javascript:;">
            <i class="icon-pointer"></i>
            <span class="title">Laporan</span>
            <span class="arrow "></span>
        </a>
        <ul class="sub-menu">
            <li>
                <a href="maps_google.html">
                    Detail Kehadiran</a>
            </li>
            <li>
                <a href="maps_vector.html">
                    Rekap Kehadiran</a>
            </li>
        </ul>
    </li>
</ul>
<!-- END SIDEBAR MENU -->